cards/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'cards'
urlpatterns = [
    path(
        '<int:pk>/add-card',
        login_required(views.AddCardView.as_view()),
        name='add-card'
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

komitet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('komitets.urls')),
    path('', include('users.urls')),
    path('', include('cards.urls')),
]

users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'users'
urlpatterns = [
    path('login',
         views.LogInView.as_view(),
         name='login'),
    path('logout',
         views.LogOutView.as_view(),
         name='logout'),
    path('signup',
         views.SignUpView.as_view(),
         name='signup'),
    path('activate/<str:uidb64>/<str:token>',
         views.ActivateUserView.as_view(),
         name='activate'),
    path('reset-password',
         views.ResetPasswordRequestView.as_view(),
         name='reset-password-request'),
    path('reset-password/<str:uidb64>/<str:token>',
         views.ResetPasswordView.as_view(),
         name='reset-password'),
    path('user/<int:pk>',
         login_required(views.UserDetailView.as_view()),
         name='user-detail'),
    path('user/<int:pk>/edit',
         login_required(views.EditUserView.as_view()),
         name='user-edit')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
import django.contrib.auth.models as auth_models
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(
        auth_models.User,
        on_delete=models.CASCADE,
        default=None
    )
    photo = models.ImageField(null=True, blank=True)


class UserPermissions(models.Model):
    PERMISSIONS = (
        ('A', 'Admin'),
        ('RW', 'Read/Write'),
        ('R', 'Read'),
        ('B', 'Banned'),
    )
    user = models.ForeignKey(auth_models.User, on_delete=models.CASCADE)
    committee = models.ForeignKey('komitets.Committee',
                                  on_delete=models.CASCADE)
    permission = models.CharField(max_length=10, choices=PERMISSIONS)


def set_permission(self, committee, permission):
    user_permission = UserPermissions.objects.get(user=self, committee=committee)
    user_permission.permission = permission
    user_permission.save()


def get_name(self):
    if self.first_name or self.last_name:
        return self.first_name + ' ' + self.last_name
    return self.username


auth_models.User.add_to_class('get_name', get_name)
auth_models.User.add_to_class('set_permission', set_permission)

users/forms.py
from django import forms
from django.contrib.auth import forms as auth_form, password_validation
from django.contrib.auth.models import User


class LogInForm(auth_form.AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', })
    )


class SignUpForm(auth_form.UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', })
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', })
    )
    username = auth_form.UsernameField(
        widget=forms.TextInput(attrs={'class': 'form-control', })
    )
    email = forms.EmailField(
        max_length=100,
        widget=forms.EmailInput(attrs={'class': 'form-control', })
    )
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', })
    )
    password2 = forms.CharField(
        label='Confirm password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', })
    )

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects \
            .filter(email=email) \
            .exclude(username=username) \
            .exists():
            raise forms.ValidationError('Email address must be unique.')
        return email


class RequestResetPasswordForm(auth_form.PasswordResetForm):
    email = forms.EmailField(
        max_length=100,
        widget=forms.EmailInput(attrs={'class': 'form-control', })
    )


class ResetPasswordForm(auth_form.SetPasswordForm):
    new_password1 = forms.CharField(
        label='New password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', }),
        strip=False,
    )
    new_password2 = forms.CharField(
        label='New password confirmation',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', }),

    )


class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', })
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', })
    )
    username = auth_form.UsernameField(
        widget=forms.TextInput(attrs={'class': 'form-control', })
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username']

users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, \
    LogoutView, PasswordResetView
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views import generic

from komitets.models import Committee
from .utils import send_confirmation_email
from .forms import LogInForm, SignUpForm, \
    RequestResetPasswordForm, ResetPasswordForm, EditUserForm
from .tokens import account_activation_token as aat, \
    password_reset_token as prt


class LogInView(LoginView):
    template_name = 'users/login.html'
    authentication_form = LogInForm

    def get(self, request, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('komitets:main'))
        else:
            return super().get(request)

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(user=username, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


class LogOutView(LogoutView):
    next_page = reverse_lazy('users:login')


class SignUpView(generic.CreateView):
    template_name = 'users/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('users:login')

    def get(self, request, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('komitets:main'))
        else:
            return super().get(request)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.email = form.cleaned_data['email']
        user.save()
        send_confirmation_email(self.request, user, form.cleaned_data['email'])
        return render(
            self.request, 'users/account_info.html',
            context={'message': 'Please confirm your email address'
                                ' to complete the registration.'}
        )


class ActivateUserView(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(kwargs['uidb64']))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None \
            and aat.check_token(user, kwargs['token']):
            user.is_active = True
            user.save()
            return render(
                self.request, 'users/account_info.html',
                context={'message': 'Thank you for your email confirmation.'
                                    ' Now you can login your account.'}
            )
        else:
            return render(self.request, 'users/account_info.html',
                          context={'message': 'Activation link is invalid!'})


class ResetPasswordRequestView(PasswordResetView):
    form_class = RequestResetPasswordForm
    template_name = 'users/reset_password_request.html'

    def form_valid(self, form):
        email = form.cleaned_data['email']
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            return render(
                self.request, 'users/account_info.html',
                context={'message': 'Please check your '
                                    'email to reset password.'}
            )
        send_confirmation_email(self.request, user, email, reset_password=True)
        return render(self.request, 'users/account_info.html',
                      context={'message': 'Please check your email'
                                          ' to reset password.'})


class ResetPasswordView(generic.TemplateView):
    template_name = 'users/password_reset.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('komitets:main'))
        try:
            uid = force_text(urlsafe_base64_decode(kwargs['uidb64']))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is None or not prt.check_token(user, kwargs['token']):
            return render(
                self.request, 'users/account_info.html',
                context={'message': 'Password reset link is invalid!'}
            )
        return render(self.request, 'users/password_reset.html',
                      context={'form': ResetPasswordForm(user)})

    def post(self, request, *args, **kwargs):
        try:
            uid = urlsafe_base64_decode(kwargs['uidb64'])
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        data = {
            'new_password1': request.POST['new_password1'],
            'new_password2': request.POST['new_password2'],
        }
        form = ResetPasswordForm(
            user=user,
            data=data
        )
        if user is not None and prt.check_token(user, kwargs['token']):
            if form.is_valid():
                user.set_password(data['new_password1'])
                user.save()
                return render(
                    self.request, 'users/account_info.html',
                    context={
                        'message': 'Your password was successfuly changed.'
                                   ' Now you can login.'})
            return render(self.request, 'users/password_reset.html',
                          context={'form': form})
        return render(self.request, 'users/account_info.html',
                      context={'message': 'Password reset\
                                   link is invalid!'})


class UserDetailView(generic.DetailView):
    model = User
    template_name = 'users/user_detail.html'
    context_object_name = 'user_profile'

    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        user = self.request.user
        data['komitets'] = Committee.objects.committees(user=user)
        data['user'] = user
        data['user_info'] = user.userprofile
        return data


class EditUserView(generic.UpdateView):
    model = User
    form_class = EditUserForm
    template_name = 'users/user_edit.html'

    def get_success_url(self):
        return reverse('users:user-detail',
                       kwargs={'pk': self.request.user.id})

    def get_context_data(self, **kwargs):
        if self.kwargs['pk'] == self.request.user.id:
            data = super().get_context_data()
            user = self.request.user
            data['komitets'] = Committee.objects.committees(user=user)
            data['user'] = user
            data['user_info'] = user.userprofile
            return data
        raise PermissionDenied

users/templates/users/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

users/templates/users/account_activation_info.html
{% extends 'users/auth_base.html' %}

{% block login-form %}
    <div class="align-content-center">
        <i class="fas fa-envelope fa-10x"></i>
        <p>{{ message }}</p>

    </div>
    <a href="{% url 'users:login' %}" class="btn btn-link">Back to Log In page</a>
{% endblock %}

users/templates/users/account_info.html
{% extends 'users/auth_base.html' %}

{% block login-form %}
    <div class="align-content-center">
        <i class="fas fa-envelope fa-10x"></i>
        <p>{{ message }}</p>

    </div>
    <a href="{% url 'users:login' %}" class="btn btn-link">Back to Log In page</a>
{% endblock %}

users/templates/users/auth_base.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="logo">Komitet</div>

    <div class="row login-centered">
        <p class="tagline">Easily solve questions in big & small communities</p>
        <div class="login-form">
            {% block login-form %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'users/auth_base.html' %}
{% block login-form %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <button type="submit" class="btn btn-primary">Log in</button>
            <a href="{% url 'users:reset-password-request' %}" class="btn btn-link mb-2">Forgot password?</a>
        </div>
        <a href="{% url 'users:signup' %}" class="btn btn-link">Join us!</a>
    </form>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'users/auth_base.html' %}
{% block login-form %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Confirm</button>
        <a href="{% url 'users:login' %}" class="btn btn-link">Log in</a>
    </form>
{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to reset your password:

http://{{ domain }}{% url 'users:reset-password' uidb64=uid token=token %}
{% endautoescape %}

users/templates/users/reset_password_request.html
{% extends 'users/auth_base.html' %}
{% block login-form %}
    <h3>Reset password</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Send email</button>
        <a href="{% url 'users:login' %}" class="btn btn-link">Log in</a>
    </form>
{% endblock %}

users/templates/users/signup.html
{% extends 'users/auth_base.html' %}
{% block login-form %}
    <h3>Registration</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Sign up</button>
        <a href="{% url 'users:login' %}" class="btn btn-link">Already have account?</a>
    </form>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'komitets/app_base.html' %}
{% load static %}

{% block komitet-detail %}
    <div class="ml-5 mt-5">
        <div class="row">
            <h2>{{ user_profile.get_name }}</h2>
            {% if user_profile == user %}
                <div><a href="{% url 'users:user-edit' pk=user_profile.id %}" class="btn btn-primary ml-3">Edit</a></div>
            {% endif %}
            <img src="{{ MEDIA_URL }}/media/{{ user_info.photo }}" alt="">
        </div>
        <div class="row">Username: {{ user_profile.username }}</div>
        <div class="row">Email: {{ user_profile.email }}</div>
        <div class="row">Last login: {{ user_profile.last_login }}</div>
        <div class="row">Joined: {{ user_profile.date_joined }}</div>
    </div>

{% endblock %}

users/templates/users/user_edit.html
{% extends 'komitets/app_base.html' %}
{% load static %}

{% block komitet-detail %}
    <div class="ml-3 mt-3">
        <div class="row">
            <h2>Edit {{ user_profile.get_name }}</h2>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Confirm</button>
        </form>
    </div>

{% endblock %}