cards/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'cards'
urlpatterns = [
    path(
        '<int:pk>/add-card',
        login_required(views.AddCardView.as_view()),
        name='add-card'
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

komitet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('komitets.urls')),
    path('', include('users.urls')),
    path('', include('cards.urls')),
]

komitets/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'komitets'
urlpatterns = [
    path(
        '',
        login_required(views.MainView.as_view()),
        name='main'
    ),
    path(
        '<int:pk>',
        login_required(views.KomitetDetailView.as_view()),
        name='komitet-detail'
    ),
    path(
        '<int:pk>/add-users',
        login_required(views.AddUsersView.as_view()),
        name='komitet-add-users'
    ),
    path(
        '<int:pk>/delete',
        login_required(views.DeleteKomitetView.as_view()),
        name='komitet-delete'
    ),
    path(
        'new-komitet',
        login_required(views.CreateKomitetView.as_view()),
        name='create-komitet'
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'users'
urlpatterns = [
    path('login',
         views.LogInView.as_view(),
         name='login'),
    path('logout',
         views.LogOutView.as_view(),
         name='logout'),
    path('signup',
         views.SignUpView.as_view(),
         name='signup'),
    path('activate/<str:uidb64>/<str:token>',
         views.ActivateUserView.as_view(),
         name='activate'),
    path('reset-password',
         views.ResetPasswordRequestView.as_view(),
         name='reset-password-request'),
    path('reset-password/<str:uidb64>/<str:token>',
         views.ResetPasswordView.as_view(),
         name='reset-password'),
    path('user/<int:pk>',
         login_required(views.UserDetailView.as_view()),
         name='user-detail'),
    path('user/<int:pk>/edit',
         login_required(views.EditUserView.as_view()),
         name='user-edit')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

komitets/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q

from .managers import CommitteeManager
from users.models import UserPermissions


class Committee(models.Model):
    members = models.ManyToManyField(User, through=UserPermissions)
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=250, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    background = models.ImageField(null=True, blank=True)
    access_code = models.CharField(max_length=10)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = CommitteeManager()

    def get_admins(self):
        return self.members.filter(userpermissions__permission='A')

    def get_writers(self):
        return self.members.filter(Q(userpermissions__permission='A')
                                   | Q(userpermissions__permission='RW'))

    def get_banned(self):
        return self.members.filter(userpermissions__permission='B')

    def get_not_banned(self):
        return self.members.exclude(userpermissions__permission='B')

komitets/forms.py
from django import forms


class CreateKomitetForm(forms.Form):
    title = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control', })
    )
    description = forms.CharField(
        max_length=50,
        widget=forms.Textarea(attrs={'class': 'form-control', })
    )
    image = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-control', })
    )


class InviteUserToKomitetForm(forms.Form):
    email = forms.EmailField(
        label='',
        widget=forms.EmailInput(attrs={'class': 'form-control col-10 m-auto'})
    )


InviteUserFormSet = forms.formset_factory(InviteUserToKomitetForm, max_num=500)

komitets/views.py
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from cards.models import Card, AnswerOption, Answer
from users.models import UserPermissions
from .forms import CreateKomitetForm, InviteUserFormSet
from .models import Committee
from .utils import send_invitation_email


class MainView(generic.ListView):
    template_name = 'komitets/app_base.html'
    context_object_name = 'komitets'

    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        data['user'] = self.request.user
        return data

    def get_queryset(self):
        return Committee.objects.committees(user=self.request.user)


class KomitetDetailView(generic.DetailView):
    template_name = 'komitets/komitet_detail.html'
    model = Committee
    context_object_name = 'komitet'

    def get_context_data(self, **kwargs):
        if self.request.user in self.object.get_not_banned():
            data = super().get_context_data()
            data['komitets'] = Committee.objects.committees(
                user=self.request.user
            )
            cards = Card.objects.filter(committee=self.object)
            data['users'] = self.object.get_not_banned()
            data['user'] = self.request.user
            data['admins'] = self.object.get_admins()
            data['writers'] = self.object.get_writers()
            data['cards'] = cards
            data['options'] = AnswerOption.objects.filter(card__in=cards)
            return data
        raise PermissionDenied

    def post(self, request, *args, **kwargs):
        post = dict(request.POST)
        del post['csrfmiddlewaretoken']
        if 'user-management' in post:
            del post['user-management']
            for key, value in post.items():
                user = User.objects.get(pk=int(key))
                committee = Committee.objects.get(pk=self.kwargs['pk'])
                user.set_permission(committee, value[0])
                return HttpResponseRedirect(reverse(
                    'komitets:komitet-detail',
                    kwargs={'pk': kwargs['pk']}
                ))
        answers_to_save = []
        key_to_delete = ''
        for key, value in post.items():
            card = Card.objects.get(pk=int(key))
            if card.type == 'YNPOLL':
                option = AnswerOption.objects.get(
                    card=card,
                    answer_content=value[0]
                )
                key_to_delete = key
                answers_to_save.append(
                    Answer(answer_option=option,
                           user=self.request.user)
                )
        if key_to_delete:
            del post[key_to_delete]
        answers_to_save.extend(
            [Answer(answer_option=AnswerOption.objects.get(pk=option_id),
                    user=self.request.user)
             for _, value in post.items()
             for option_id in value]
        )
        Answer.objects.bulk_create(answers_to_save)
        return HttpResponseRedirect(reverse(
            'komitets:komitet-detail',
            kwargs={'pk': kwargs['pk']}
        ))


class CreateKomitetView(generic.FormView):
    template_name = 'komitets/create_komitet.html'
    form_class = CreateKomitetForm

    def form_valid(self, form):
        image = self.request.FILES['image'] if 'image' in self.request.FILES \
            else None
        komitet = Committee(
            title=form.cleaned_data['title'],
            description=form.cleaned_data['description'],
            image=image
        )
        komitet.save()
        komitet.refresh_from_db()
        permission = UserPermissions.objects.create(
            user=self.request.user,
            committee=komitet,
            permission='A'
        )
        permission.save()
        return HttpResponseRedirect(
            reverse('komitets:komitet-add-users', kwargs={'pk': komitet.id})
        )

    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        user = self.request.user
        data['komitets'] = Committee.objects.committees(user=user)
        data['user'] = user
        return data


class AddUsersView(generic.FormView):
    template_name = 'komitets/add_users.html'
    form_class = InviteUserFormSet

    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        user = self.request.user
        committee = Committee.objects.get(pk=self.kwargs.get('pk'))
        data['komitets'] = Committee.objects.committees(user=user)
        data['komitet'] = committee
        data['user'] = user
        data['users'] = committee.get_not_banned()
        data['admins'] = committee.get_admins()
        return data

    def form_valid(self, formset):
        committee = Committee.objects.get(pk=self.kwargs['pk'])
        if self.request.user in committee.get_not_banned():
            emails_to_invite = []
            for data in formset.cleaned_data:
                try:
                    user = User.objects.get(email=data['email'])
                    try:
                        UserPermissions.objects \
                            .get(user=user.id, committee=committee.id)
                    except UserPermissions.DoesNotExist:
                        UserPermissions.objects.create(
                            user=user,
                            committee=committee,
                            permission='RW'
                        )
                except User.DoesNotExist:
                    emails_to_invite.append(data['email'])
                except KeyError:
                    pass
            if emails_to_invite:
                send_invitation_email(
                    self.request,
                    emails_to_invite,
                    self.kwargs['pk']
                )
            return HttpResponseRedirect(reverse(
                'komitets:komitet-detail',
                kwargs={'pk': committee.id}
            ))
        raise PermissionDenied


class DeleteKomitetView(generic.DeleteView):
    model = Committee
    template_name = 'komitets/delete.html'
    success_url = reverse_lazy('komitets:main')
    context_object_name = 'komitet'

    def get_context_data(self, **kwargs):
        if self.request.user in self.object.get_admins():
            data = super().get_context_data()
            user = self.request.user
            data['komitets'] = Committee.objects.committees(user=user)
            data['user'] = user
            data['users'] = self.object.get_not_banned()
            return data
        raise PermissionDenied

komitets/templates/komitets/add_users.html
{% extends 'komitets/app_base.html' %}

{% load static %}

{% block komitet-detail %}
    <h3>Invite users to Komitet</h3>
    <form method="post">
        {% csrf_token %}
        <h4>Email: </h4>
        {{ form.management_form }}
        {% for f in form %}
            <div id="inputs">
                <div class="row mb-3">
                    {{ f }}
                    <button type="button" id="rmBtn" class="btn btn-danger m-auto" onclick="delRequest(this)"><i class="fas fa-trash"></i>
                    </button>
                </div>
            </div>
            <div class="row" id="buttonsDiv">
                <button type="button" id="addBtn" class="btn btn-success m-auto"><i class="fas fa-plus"></i></button>
                <button type="submit" class="btn btn-success m-auto">Invite</button>
            </div>
        {% endfor %}
    </form>
    <script type="application/javascript" src="{% static 'komitets/js/formset.js' %}"></script>
{% endblock %}

komitets/templates/komitets/app_base.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <div class="container-fluid without-margins">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand"
               href="{% url 'komitets:main' %}">Komitet</a>
            <a href="{% url 'komitets:create-komitet' %}"
               class="btn btn-success ml-auto mr-3 btn-sm"><i
                    class="fas fa-plus"></i>
                Add Komitet</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto mr-5">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#"
                           id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true"
                           aria-expanded="false">
                            {{ user.get_name }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right"
                             aria-labelledby="navbarDropdown">
                            <a class="dropdown-item"
                               href="{% url 'users:user-detail' pk=user.id %}">Profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item"
                               href="{% url 'users:logout' %}">Log out</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="komitets-list">
                {% for kom in komitets %}
                    {% if kom.id == komitet.id %}
                        <a href="{% url 'komitets:komitet-detail' pk=komitet.id %}"
                           class="active-komitet"><img
                                {% if kom.image %}
                                    src="/media/{{ kom.image }}"
                                {% else %}
                                    src="http://via.placeholder.com/50?text={{ kom.title|make_list|slice:':2'|join:''|upper }}"
                                {% endif %}
                                    class="rounded-circle mb-1 mt-1 small-photo"
                                    alt=""></a>
                    {% else %}
                        <a href="{% url 'komitets:komitet-detail' pk=kom.id %}"><img
                                {% if kom.image %}
                                    src="/media/{{ kom.image }}"
                                {% else %}
                                    src="http://via.placeholder.com/50?text={{ kom.title|make_list|slice:':2'|join:''|upper }}"
                                {% endif %}
                                    class="rounded-circle mb-1 mt-1 small-photo"
                                    alt=""></a>

                    {% endif %}

                {% endfor %}
            </div>
            <div class="komitet-users col-2">
                {% block komitet-users %}
                    {% for usr in users %}
                        <div class="dropdown">
                            <button class="btn btn-link p-0"
                                    type="button" id="user{{ usr.id }}"
                                    data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                <img
                                        {% if usr.photo %}
                                            src="{{ MEDIA_URL }}/media/{{ usr.photo }}"
                                        {% else %}
                                            src="http://via.placeholder.com/50?text={{ usr.get_name|make_list|slice:':2'|join:''|upper }}"
                                        {% endif %}
                                            class="rounded-circle ml-2 mb-1 mt-1 small-photo"
                                            alt="">
                                <span class="centered-username ml-2">
                                    {{ usr.get_name }}{% if usr in admins %}
                                        <i class="fas fa-star"></i>{% endif %}
                                </span>
                            </button>
                            <div class="dropdown-menu"
                                 aria-labelledby="user{{ usr.id }}">
                                <a class="dropdown-item"
                                   href="{% url 'users:user-detail' pk=usr.id %}">Profile</a>
                                {% if user in komitet.get_admins %}
                                    <form method="post">
                                        {% csrf_token %}
                                        <div class="dropdown-divider"></div>
                                        <input type="hidden"
                                               name="user-management"
                                               value="True">
                                        <input type="hidden"
                                               name="{{ usr.id }}">
                                        <button class="dropdown-item" value="A"
                                                onclick="manageUser(this)">Make
                                            admin
                                        </button>
                                        <button class="dropdown-item" value="RW"
                                                onclick="manageUser(this)">Allow read/write
                                        </button>
                                        <button class="dropdown-item" value="R"
                                                onclick="manageUser(this)">
                                            Forbid write
                                        </button>
                                        <button class="dropdown-item" value="B"
                                                onclick="manageUser(this)">Ban
                                        </button>

                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                    <script type="application/javascript"
                            src="{% static 'komitets/js/manage_users.js' %}"></script>
                {% endblock %}
            </div>
            <div class="komitet-main col-5">
                {% block komitet-detail %}
                    <div class="mt-5 ml-5"><h2><i
                            class="fas fa-angle-left"></i> Choose Komitet</h2>
                    </div>
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

komitets/templates/komitets/create_komitet.html
{% extends 'komitets/app_base.html' %}


{% block komitet-detail %}
    <h3>Create komitet</h3>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form.as_p }}
    <button type="submit" class="btn btn-success">Create</button>
    </form>
{% endblock %}

komitets/templates/komitets/delete.html
{% extends 'komitets/app_base.html' %}


{% block komitet-detail %}
    <h3 class="mt-5 mb-5">Are you sure want to delete komitet {{ komitet.title }}</h3>
    <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirm</button>
        <a class="btn btn-secondary" href="{% url 'komitets:komitet-detail' pk=komitet.id %}">Back</a>
    </form>
{% endblock %}

komitets/templates/komitets/invitation_email.html
{% autoescape off %}
Hi!

You have been invited by {{ user.username }} to Komitet, for more information check out link below

http://{{ domain }}{% url 'komitets:komitet-detail' pk=pk %}
{% endautoescape %}